import type { AgentSpec, ExtractedItem } from "./types.js";
import { isGrantTarget } from "./opportunity-subtype.js";

function str(v: unknown): string {
  return String(v ?? "").trim();
}

function looksLikeGrant(item: ExtractedItem): boolean {
  if (str(item.program_name) || str(item.max_funding) || str(item.deadline)) return true;
  if (str(item.organization) && str(item.description)) return true;
  const blob = `${item.title ?? ""} ${item.summary ?? ""} ${item.description ?? ""} ${item.reason ?? ""}`.toLowerCase();
  return /\b(grant|funding|subvenci|convocatoria|up to \$|up to €|deadline|closing)\b/i.test(blob);
}

function grantLine(item: ExtractedItem): string {
  const title = str(item.program_name) || str(item.title) || "Untitled grant";
  const funding =
    str(item.max_funding) ||
    str(item.description) ||
    str(item.summary) ||
    str(item.reason) ||
    "Open opportunity — see link for details.";
  const org = str(item.organization);
  const deadline = str(item.deadline);
  const bits = [funding];
  if (org) bits.push(`Org: ${org}`);
  if (deadline) bits.push(`Deadline: ${deadline}`);
  const url = str(item.url);
  return url ? `${title}\n${bits.join(" · ")}\n${url}` : `${title}\n${bits.join(" · ")}`;
}

function newsLine(item: ExtractedItem, index: number): string {
  const title = str(item.title) || str(item.headline) || `Item ${index + 1}`;
  const news =
    str(item.summary) ||
    str(item.description) ||
    str(item.the_news) ||
    str(item.reason) ||
    "";
  const why = str(item.why_it_may_matter) || str(item.why_it_matters) || "";
  const source = str(item.source) || str(item.organization) || "";
  const date = str(item.publication_date) || str(item.date) || "";
  const url = str(item.url) || str(item.plain_url) || "";
  const parts = [`${index + 1}. ${title}`];
  if (news) parts.push(`• The News: ${news}`);
  if (why) parts.push(`• Why it Matters: ${why}`);
  if (source) parts.push(`• Source: ${source}`);
  if (date) parts.push(`• Date: ${date}`);
  if (url) parts.push(`• Link: ${url}`);
  return parts.join("\n");
}

/** Detect wrap-up / newsletter style agents from prompt + destinations. */
export function isNewsletterWrapTarget(spec: AgentSpec): boolean {
  if (spec.output.destinations.includes("email")) return true;
  const blob = `${spec.prompt} ${spec.name} ${spec.filters.criteria}`.toLowerCase();
  return /\b(wrap-?up|newsletter|bolet[ií]n|changemaker|impact news|business for good|bfgn)\b/i.test(
    blob
  );
}

/**
 * Compose a BFGN-style plain-text wrap (grants block + news block) for email draft / inbox.
 */
export function composeNewsletterWrap(
  items: ExtractedItem[],
  spec: AgentSpec,
  options?: { monthLabel?: string; maxGrants?: number; maxNews?: number }
): string {
  const month =
    options?.monthLabel ??
    new Date().toLocaleString("en-AU", { month: "long", year: "numeric" });
  const maxGrants = options?.maxGrants ?? 12;
  const maxNews = options?.maxNews ?? 10;

  const grants = items.filter(looksLikeGrant).slice(0, maxGrants);
  const news = items.filter((i) => !looksLikeGrant(i)).slice(0, maxNews);
  // If everything looked like grants (pure grant agent), still emit news-less wrap.
  const grantBlock =
    grants.length > 0
      ? grants.map(grantLine).join("\n\n")
      : isGrantTarget(spec)
        ? items.slice(0, maxGrants).map(grantLine).join("\n\n")
        : "(No open grant listings found this run.)";

  const newsSource = grants.length > 0 ? news : isGrantTarget(spec) ? [] : items.slice(0, maxNews);
  const newsBlock =
    newsSource.length > 0
      ? newsSource.map((item, i) => newsLine(item, i)).join("\n\n")
      : "(No sector news items ranked this run.)";

  return [
    `${month}`,
    spec.name,
    "",
    `Hi,`,
    "",
    `The wrap-up is here — opportunities and news gathered for you.`,
    "",
    `=== Open grants & funding ===`,
    "",
    grantBlock,
    "",
    `=== Business for good news wrap-up ===`,
    "",
    newsBlock,
    "",
    `—`,
    `Generated by AIIA · ${new Date().toISOString().slice(0, 10)}`,
    `Agent: ${spec.name}`,
  ].join("\n");
}

/** Build a minimal RFC 822 .eml draft (open in Outlook / Mail). */
export function buildEmlDraft(options: {
  subject: string;
  body: string;
  to?: string;
  from?: string;
}): string {
  const to = options.to?.trim() || "undisclosed-recipients:;";
  const from = options.from?.trim() || "AIIA <aiia@localhost>";
  const subject = options.subject.replace(/[\r\n]+/g, " ").slice(0, 180);
  // Quoted-printable-ish plain: keep UTF-8 and encode as base64 if non-ascii heavy.
  const needsB64 = /[^\x00-\x7F]/.test(options.body) || /[^\x00-\x7F]/.test(subject);
  if (needsB64) {
    const b64 = Buffer.from(options.body, "utf8").toString("base64");
    const subjB64 = `=?UTF-8?B?${Buffer.from(subject, "utf8").toString("base64")}?=`;
    return [
      `From: ${from}`,
      `To: ${to}`,
      `Subject: ${subjB64}`,
      `MIME-Version: 1.0`,
      `Content-Type: text/plain; charset=UTF-8`,
      `Content-Transfer-Encoding: base64`,
      `Date: ${new Date().toUTCString()}`,
      `X-Mailer: AIIA`,
      ``,
      b64.match(/.{1,76}/g)?.join("\r\n") ?? b64,
      ``,
    ].join("\r\n");
  }
  return [
    `From: ${from}`,
    `To: ${to}`,
    `Subject: ${subject}`,
    `MIME-Version: 1.0`,
    `Content-Type: text/plain; charset=UTF-8`,
    `Content-Transfer-Encoding: 8bit`,
    `Date: ${new Date().toUTCString()}`,
    `X-Mailer: AIIA`,
    ``,
    options.body.replace(/\n/g, "\r\n"),
    ``,
  ].join("\r\n");
}
